kumuluzee:
  name: rso-review
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8085
    http:
      port: 8085
  datasources:
    - jndi-name: jdbc/ReviewDS
      connection-url: jdbc:postgresql://172.17.0.1:32772/reviews
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
       hosts: http://192.168.99.100:2379
  discovery:
    etcd:
       hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15
