kumuluzee:
  name: rso-recommendation
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://127.17.0.1:8087
    http:
      port: 8087
  datasources:
    - jndi-name: jdbc/RecommendationDS
      connection-url: jdbc:postgresql://172.17.0.1:32774/recommendations
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
       hosts: http://192.168.99.100:2379
  discovery:
    etcd:
       hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15
