sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean package -U
  - cd projekt-apartment
  - docker build -t kknp/rso-apartment .
  - cd ../projekt-user/
  - docker build -t kknp/rso-user .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push kknp/rso-apartment
  - docker push kknp/rso-user