kumuluzee:
  name: rso-user
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/UserDS
      connection-url: jdbc:postgresql://172.17.0.1:32769/users
      username: dbuser
      password: postgres
      max-pool-size: 20

  config:
      etcd:
        hosts: http://192.168.99.100:2379
    discovery:
      etcd:
        hosts: http://192.168.99.100:2379
    cors-filter:
      servlet:
        allow-origin: "*"
    health:
        checks:
          data-source-health-check:
            jndi-name: jdbc/UserDS
          servlet:
            mapping: /health
            enabled: true
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="customers">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                            <Socket name="logstash" host="ee4660e4-288e-4a4d-8111-82c8bcc0ab79-ls.logit.io" port="16232" protocol="tcp">
                                <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                            </Socket>
                        </Appenders>
                        <Loggers>
                            <!-- Default logger -->
                            <Root level="all">
                                <AppenderRef ref="console" level="info"/>
                                <AppenderRef ref="logstash" level="trace"/>
                            </Root>
                        </Loggers>
                    </Configuration>'
  rest-properties:
    healthy: true