kumuluzee:
  name: rso-apartment
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/ApartmentDS
      connection-url: jdbc:postgresql://172.17.0.5:32768/apartment
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://172.17.0.5:2379
  discovery:
    etcd:
      hosts: http://172.17.0.5:2379
    ttl: 20
    ping-interval: 15