apiVersion: v1
kind: Service
metadata:
  name: apartment
  labels:
      app: apartment
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: apartment