apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rent-availability
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rent
    spec:
      containers:
      - image: kknp/rso-availability:latest
        name: rent
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: minikube
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-availability:5432/availability
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
          name: server
          protocol: TCP