apiVersion: v1
kind: Service
metadata:
  name: avaliability
  labels:
      app: avaliability
spec:
  type: LoadBalancer
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: avaliability