apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - image: kknp/rso-payment:latest
        name: payment
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: minikube
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-payment:5432/payment
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
          name: server
          protocol: TCP
        resources:
          limits:
            cpu: 400m
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 40
          periodSeconds: 5