apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
      app: payment
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: payment