apiVersion: v1
kind: Service
metadata:
  name: postgres-recommendation
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-recommendation
