apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: projekt-user-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
      - image: projekt-user:v1
        name: projekt-user
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: minikube
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP