apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: recommendation-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
      - image: kknp/rso-recommendation:latest
        name: recommendation
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: minikube
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-recommendation:5432/recommendation
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
          name: server
          protocol: TCP