apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
      app: user
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: user