kumuluzee:
  name: rso-rent
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://172.17.0.1:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/RentDS
      connection-url: jdbc:postgresql://172.17.0.1:32770/rents
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
       hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15
  cors-filter:
    servlet:
      allow-origin: "*"
  streaming:
    kafka:
      producer:
        bootstrap-servers: 192.168.99.100:9092
        acks: all
        retries: 0
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer