kumuluzee:
  name: rso-event
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://172.17.0.1:8086
    http:
      port: 8086
  datasources:
    - jndi-name: jdbc/EventDS
      connection-url: jdbc:postgresql://172.17.0.1:32773/events
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
       hosts: http://192.168.99.100:2379
  discovery:
    etcd:
       hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15
  streaming:
    kafka:
      consumer:
        bootstrap-servers: velomobile-01.srvs.cloudkafka.com:9094
        group-id: group1
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        security-protocol: SASL_SSL
        sasl-mechanism: SCRAM-SHA-256
        sasl-jaas-config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="lbu290s1" password="47YuTfNEY2qOXgcIYcEW-eX36rDJD0pX";'
        group-id: newer
